### ISSUE TITLE
How to train own data?

### ISSUE THREAD

**Issue by pipisjy** [pranavkdm/R-PointHop#2]
Could you tell me how to train the network using my own data ?
Just change the train_data in the train.py ?

**Comment by pranavkdm** [comment]
> Could you tell me how to train the network using my own data ?
> Just change the train_data in the train.py ?

You have to pass train_data as a parameter to rpointhop.pointhop_train() in train.py. The train_data is a numpy array of shape (B,N,3), where is B is number of point cloud objects, N is number of points in each point cloud and 3 is for the point coordinates. In case your point clouds contain different number of points, be sure to sample the point cloud to same number of points. The furthest_point_sample() function in point_utils.py may be useful to do so.

**Comment by pipisjy** [comment]
Thank you for your response,i will try it again.

**Comment by pipisjy** [comment]
Sorry to bother again. When i was training my own data, i found the number of my point cloud (B) was too large to run the code. How can i modify the code ?

**Comment by pranavkdm** [comment]
> Sorry to bother again. When i was training my own data, i found the number of my point cloud (B) was too large to run the code. How can i modify the code ?

How much large? The code should run irrespective of the number of point clouds. It might take longer time though. Any memory errors mostly may be related to smaller size of RAM which prohibits processing of larger numpy arrays. You may want to reduce the number of points in each point cloud. For training our model, we used 1024 points sampled randomly from each point cloud.

**Comment by pipisjy** [comment]
I take 20K points into training

**Comment by pranavkdm** [comment]
> I take 20K points into training

Yes. That is too large to handle. Please try a subset of points.
